name: Prisma Cloud Scaning
on:
  #push:
  push:
    branches:
      - master
      - main
    #branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    #branches: [ main ]
env:
  PRISMA_API_URL: https://api.eu.prismacloud.io/

jobs:
   bridgecrew:
    runs-on: ubuntu-latest
    steps:
    - name: Run checkov
      id: checkov
      uses: bridgecrewio/checkov-action@master
      env:
        PRISMA_API_URL: ${{ env.PRISMA_API_URL }}
      with:
        directory: .
        api-key: ${{ secrets.PC_API_KEY }}
