name: Prisma Cloud Scaning
on:
  #push:
  push:
    branches:
      - master
    #branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    #branches: [ main ]
jobs:
   bridgecrew:
    runs-on: ubuntu-latest
    steps:
    - name: Run checkov
      id: checkov
      uses: bridgecrewio/checkov-action@master
      env:
        GITHUB_TOKEN: ${{secrets.PC_API_KEY}}
